
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-09T17:54:05-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "2c50bcffba01133702a6f1759b837c6c4ea994d5",
 "version": "2.4.0+5.g2c50bcf"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
